import Head from "next/head";
import HomePage from "./home";
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Hospitality Finder | Best place to find chefs &#38; kitchen staff
        </title>
        <meta
          name="google-site-verification"
          content="U9krkvRqVdLJaS2guCqqLrKDp9px9kZxVybkZDqcJt8"
        />
        <meta
          name="description"
          content="Hospitality Finder is the best place to find chefs and kitchen staff for your cooking and hospitality industry needs. It is the largest online professional chef network, connecting hotels and restaurants with qualified and experienced chefs and cooks in India, US and UK."
        />
        <meta
          name="Keywords"
          content="Hire Qualified &#38; Experienced Chefs,
          Online professional chef,
          Hire qualified Chefs,
          Best place to find chefs &#38; kitchen staff,
          Hire Cooks and Chefs,
          Hire a personal Chef,
          How to find cooks for my restaurant,
          Chef for Hire,
          Tips For Hiring A Great Chef,
          Famous Chefs for Hire,
          Hire Chefs online,
          How to find good Chef near me,
          Best Chef for my restaurant,
          Looking Chef for my restaurant,
          Guide to Hiring a Personal Chef,
          Professional Chefs,
          Professional chef for home,
          Professional chefs near me,
          Find &#38; Hire Chefs Near Me,
          Hire a chef near me,
          How to Hire the Best Chefs,
          Hire a personal Cook or Chef,
          Looking for a chef,
          List of Famous Chefs,
          The Master Chefs,
          Need Chef for restaurant,
          Where to find Cooks,
          Chef for hire near me,
          I want to hire A Chef,
          Chefs near me"
        />

        <link rel="icon" href="/favicon.ico" />
        {/* <!-- JSON-LD markup generated by Google Structured Data Markup Helper. --> */}
        <script type="application/ld+json">
          {` "@context" : "http://schema.org",
              "@type" : "JobPosting",
              "title" : "Millions of people use Hospitality Finder to turn their ideas into reality.",
              "hiringOrganization" : "We offer you a wide variety of candidates in all fields of the hospitality business.",
              "jobLocation" : {
                "@type" : "Place",
                "address" : "CONTACT US"
              },
              "description" : "We provide you with candidates in the fields of cooking, event management, bartending, accounts, and legal, and you get all of them here.",
              "employmentType" : "hospitality industry"`}
        </script>
      </Head>

      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-JCWDGRF3JL"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);}
            gtag('js', new Date());
  
            gtag('config', 'G-JCWDGRF3JL');
          `}
      </Script>

      <HomePage />
    </>
  );
}
